spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wenrui
    password: swrswr123123
    url: jdbc:mysql://8.134.39.14:3306/demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
server:
  port: 8081